FROM maven:3.8.3-openjdk-8 as builder
RUN mkdir /app
COPY vendors/eidas-node /app/
RUN ls /app/
RUN cd /app/EIDAS-Parent \ 
 && mvn clean package -P NodeOnly,DemoToolsOnly,nodeJcacheIgnite,specificCommunicationJcacheIgnite -DskipTests

FROM tomcat:8.5-jdk8
COPY --from=builder /app/EIDAS-SpecificConnector/target/SpecificConnector.war /usr/local/tomcat/webapps/
COPY --from=builder /app/EIDAS-SpecificProxyService/target/SpecificProxyService.war /usr/local/tomcat/webapps/
COPY --from=builder /app/EIDAS-Node/target/EidasNode.war /usr/local/tomcat/webapps/
COPY --from=builder /app/EIDAS-SP/target/SP.war /usr/local/tomcat/webapps/
COPY --from=builder /app/EIDAS-IdP-1.0/target/IdP.war /usr/local/tomcat/webapps/

RUN curl -L https://www.bouncycastle.org/download/bcprov-jdk15on-164.jar -o /usr/local/tomcat/lib/bcprov-jdk15on-164.jar

RUN ls /usr/local/tomcat/webapps/
ENV JPDA_ADDRESS="0.0.0.0:8000"
ENV JPDA_TRANSPORT="dt_socket"
CMD ["catalina.sh", "jpda", "run"]

